apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: saidiwissem/web-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # Container port to match the targetPort in the service

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the service
      targetPort: 8080  # Port on the container
      nodePort: 30007   # NodePort for external access
  type: NodePort       # Service type
