apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: saidiwissem/web-app:latest  # Docker image built in Jenkins
        imagePullPolicy: Always  # Always pull the latest image
        ports:
        - containerPort: 8080  # Port the container listens on

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp  # Selects the pods with the label "app: webapp"
  ports:
  - protocol: TCP
    port: 80          # Port exposed by the service
    targetPort: 8080  # Port on the container
    nodePort: 30007   # NodePort for external access
  type: NodePort       # Exposes the service on each Node's IP at a static port
